### PR TITLE
Fix index in fetching the last unlisted run

### PR DESCRIPTION
**Pull request by stefannica**

### CODE REVIEW

**Review by htahir1 — COMMENTED** [review]
I suppose this only makes sense when we upgrade the requirements.txt to have ZenML 0.35.0

**Comment by stefannica** [comment]
> I suppose this only makes sense when we upgrade the requirements.txt to have ZenML 0.35.0

Done, but we always install the latest ZenML in the notebooks anyway, so this wasn't a problem so far.

**Review by htahir1 — APPROVED** [review]
Makes sense! Again, hope its all tested with the latest version? :-)

**Comment by stefannica** [comment]
> Makes sense! Again, hope its all tested with the latest version? :-)

Now it is :-)

**Pull request merged**
